pretranslate:
  segments:
    ignore_frontmatter_keys:
    - "menu"
    - "pizza1"
    - "pizza2"
    - "pizza3"
    - "pasta1"
    - "pasta2"
    - "pasta3"
  
  ignore_patterns:
    - !ruby/regexp /^(?!\(\)$)(.*)$/
      
  paths:
  - source: .
    include:
    - "04_11.md"
   
    
