pretranslate:
  segments:
    ignore_frontmatter_keys:
    - "menu"
    - "pizza1"
    - "name"
    - "pizza2"
    - "name"
    - "pizza3"
    - "name"
    - "pasta1"
    - "name"
    - "pasta2"
    - "name"
    - "pasta3"
    - "name"
    
  paths:
  - source: .
    include:
    - "04_11.md"
    
