pretranslate:
  segments:
    ignore_frontmatter_keys:
    - "district"
    - "house first"
    - "family"
    - "members"
    - "house second"
       
  paths:
  - source: .
    include:
    - "04_10_1.md"
    
